version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=username
      - DB_PASS=mysecretpassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydatabase
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    volumes:
      - ./migrate/init.sql:/docker-entrypoint-initdb.d/init.sql